export const mainPath = '/main';
export const dashboardPath = `${mainPath}/dashboard`;
export const networkBasePath = `${mainPath}/network-graph`;
export const listeningEndpointsBasePath = `${mainPath}/listening-endpoints`;
export const violationsBasePath = `${mainPath}/violations`;
export const complianceBasePath = `${mainPath}/compliance`;
export const vulnManagementPath = `${mainPath}/vulnerability-management`;
export const configManagementPath = `${mainPath}/configmanagement`;
export const riskBasePath = `${mainPath}/risk`;
export const riskWorkloadsBasePath = `${riskBasePath}/workloads`;
export const riskUserWorkloadsViewPath = `${riskWorkloadsBasePath}?filteredWorkflowView=Applications view`;
export const riskPlatformViewPath = `${riskWorkloadsBasePath}?filteredWorkflowView=Platform view`;
export const riskFullViewPath = `${riskWorkloadsBasePath}?filteredWorkflowView=Full view`;
export const clustersBasePath = `${mainPath}/clusters`;
export const policyManagementBasePath = `${mainPath}/policy-management`;
export const integrationsPath = `${mainPath}/integrations`;
export const accessControlBasePath = `${mainPath}/access`;
export const systemConfigPath = `${mainPath}/systemconfig`;
export const systemHealthPath = `${mainPath}/system-health`;
